### ISSUE TITLE
Add recognizing required fields added as a list

### ISSUE THREAD

**Issue by magdanowak** [aubergine-developers/nadia#3]
Add recognizing required fields when added as a list, e.g.:

```
type: `object`
required:
  - foo
properties:
    foo: integer
```

instead of:

```
type: object
   properties:
    foo:
        required: true
        integer
```
