### ISSUE TITLE
Support for oneOf, anyOf and allOf  keywords

### ISSUE THREAD

**Issue by dexter2206** [aubergine-developers/nadia#5]
Nadia should support combining schemas using oneOf, anyOf and allOf keywords.

The official [OpenAPI docs](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) can be used to provide examples/unit tests cases for this feature:

**Comment by magdanowak** [comment]
@dexter2206 The way nadia is set up now, if we try validating a anyOf/allOf schema, it's not possible for the single schemas to be valid, unless they are identical. `check_unknown_fields` will not recognize fields from the different schema, and raise an error.

Example:
```
  PetByAnythingWithoutRefs:
    anyOf:
      - type: object
        properties:
          age:
            type: integer
          nickname:
            type: string
        required:
          - age
      - type: object
        properties:
          pet_type:
            type: string
          hunts:
            type: integer
        required:
          - pet_type
```

If this schema receives an object with `age` and `pet_type`, each single schema should fail, since there are extra fields. We need to rethink the strategy here.
